"""added Files and Lines tables

Revision ID: 4b8776e457a5
Revises: 51f5ccfba190
Create Date: 2017-09-30 21:55:26.393359

"""

# revision identifiers, used by Alembic.
revision = '4b8776e457a5'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('crt_dt', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('orig_file', sa.String(length=100), nullable=False),
    sa.Column('purch_dt', sa.Date(), nullable=True),
    sa.Column('store', sa.String(length=100), nullable=True),
    sa.Column('trans_num', sa.String(length=40), nullable=True),
    sa.Column('default_discount', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('pmt_meth', sa.String(length=50), nullable=True),
    sa.Column('trans_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sub_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nei_trans_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nei_sub_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nei_tax_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nei_discount_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('lines',
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ser_id', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.String(length=150), nullable=False),
    sa.Column('series', sa.String(length=150), nullable=False),
    sa.Column('issue', sa.String(length=20), nullable=True),
    sa.Column('iss_full', sa.String(length=20), nullable=False),
    sa.Column('iss_num', sa.Integer(), nullable=False),
    sa.Column('iss_ext', sa.String(length=10), nullable=True),
    sa.Column('edition', sa.String(length=150), nullable=True),
    sa.Column('cvr_dt', sa.String(length=20), nullable=True),
    sa.Column('cvr_dt_year', sa.Integer(), nullable=True),
    sa.Column('cvr_dt_month', sa.Integer(), nullable=True),
    sa.Column('cvr_dt_day', sa.Integer(), nullable=True),
    sa.Column('cover_price', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('purch_price', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('purch_dt', sa.Date(), nullable=True),
    sa.Column('store', sa.String(length=100), nullable=True),
    sa.Column('trans_num', sa.String(length=40), nullable=True),
    sa.Column('release_dt', sa.Date(), nullable=True),
    sa.Column('crossover', sa.String(length=100), nullable=True),
    sa.Column('story_arc', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('sub_title', sa.String(length=100), nullable=True),
    sa.Column('str_seq', sa.Integer(), nullable=True),
    sa.Column('str_cvr_price', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('str_item_disc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('str_disc_price', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('taxable_ind', sa.String(length=1), nullable=True),
    sa.Column('str_item_tax', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('str_tax_adj', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('str_tax_paid', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ),
    sa.PrimaryKeyConstraint('line_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lines')
    op.drop_table('files')
    # ### end Alembic commands ###
